# 数据分析day01

### 什么是数据分析
     数据分析是指用适当的统计分析方法对收集来的大量数据进行分析，提取有用的信息形成结论而对结论加以详细研究、概括、总结的过程。

### 使用python做数据分析的常用库
    numpy 基础数值计算
    scipy 科学计算
    matplotlib 数据可视化
    pandas   序列高级函数

### numpy 概述
 1. Numerical Python, 数值的python，补充了Python语言所欠缺的数值计算能力。
 2. Numpy是其他数据分析及机器学习库的底层库。
 3. Numpy完全标准C语言实现，效率充分优化。
 4. Numpy开源免费。

### numpy的历史
    1. 1995年， Numeric发布（numpy的前身）。  
    2. 2001年，Scipy->Numarray，提供多维数组运算。
    3. 2005年，Numeric+Numarray -> Numpy
    4. 2006年，Numpy脱离Scipy称为独立项目。

### numpy核心 ：多维数组

In [1]:
import numpy as np

In [4]:
ary = np.array([1,2,3,4,5])
ary

array([1, 2, 3, 4, 5])

## numpy 基础

### ndarray 数据

In [7]:
ary = np.array([1,2,3,4,5])
print(ary)
print(type(ary))
print(ary + 10)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[11 12 13 14 15]


### 内存中的ndarray对象
  #### 元数据
     存储对目标数组的描述信息，如：dim count, dimensions, dtype, data等等。
  #### 实际数据
     完整的数组内容
     将实际数据与元数据分开存放，一方面提高了内存空间的使用效率， 另一方面减少对实际数据的访问频率， 提高效率。

### ndarray 数组对象的特点
    Numpy数组是同质数组，所有元素的数据类型必须相同。

### ndarray数组对象的创建
    np.array([任何可以被解释为数组的逻辑结构])
    np.arrange(起始值[0],终止值，步长[1])
    np.zeros(数组的个数，dtype='元素类型')
    np.ones(数组的个数，dtype='元素类型')
    np.one_like(ary)
    np.zeros_like(ary)

In [11]:
# 多维数组
a = np.array([[1,2,3,4],
            [5,6,7,8]])
print(a)
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [14]:
# 创建一个连续的数组
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# 创建10个全为0的数组
b = np.zeros(10)
print(b)
print(b.dtype)
# 修改其数据类型
c = np.zeros(10,dtype='bool')
print(c)
# 保存为int32 位的整型
d = np.zeros(3,dtype='int32')
print(d)
# 创建5个元素为1的数组
e = np.ones(4,dtype='int32')
print(e)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
float64
[False False False False False False False False False False]
[0 0 0]
[1 1 1 1]


####  创建数组e和f,结构与a相同，e中全0，f中全1

In [24]:
e = np.zeros_like(a)
f = np.ones_like(a)
print(e)
print(f)

[[0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]]


### ndarray对象属性的基本操作

#### 数组的维度
    ndarray.shape
#### 元素的类型
    ndarray.dtype
#### 数组元素的个数
    ndarray.size  len(ndarray)
#### 数组元素的索引(下标) 
    ary[0]

In [28]:
# 测试数组的维度
g = np.arange(1,10)
print(a)
print(g.shape)

[[1 2 3 4]
 [5 6 7 8]]
(9,)


In [31]:
# 修改测试数组的元素的维度
g.shape = (3,3)  # 合理的变维度是允许的 元数据没有发生变化，只是将其描述的信息发生了改变
print(g, g.shape)   

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [33]:
print(g.dtype) # 输出数组的类型
b = a.astype(float)
print(b,b.dtype)

int32
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]] float64


In [36]:
# 元素的个数
print(g.size)  # 返回元素的个数
print(len(g))  # 返回外层元素的个数

9
3


In [37]:
# 数组元素的索引
h = np.arange(1,19).reshape(3,2,3)
print(h)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [39]:
h[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
h[0][0]

array([1, 2, 3])

In [41]:
h[0][0][0]

1

In [42]:
h[0,0,0]

1

### ndarray 对象属性操作详解
    内部基本数据类型

 #### 类型名 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;类型标识符
     布尔型           bool_
     有符号整数型     int8 / int16 / int32 / int64
     无符号整数型     uint8/uint16/uint32/uint64
     浮点型           float16/float32/float64
     复数型           complex64/complex128
     字串型           str_ (每个字符32位Unicode编码)
 

### ndarray 数组中存储自定义复合类型数据

In [56]:
# 存储复杂类型的数据
data = [
    ('zs',[90,80,70],15),
    ('ls',[86,76,69],16),
    ('ww',[22,11,34],17)
] 
# 第一种设置dtype属性的方式
# U3 Unicode 字符 3 个
# 3int32  3个int32 数字
# int32   1个int32 数字
i = np.array(data,dtype='U3, 3int32, int32')
i

array([('zs', [90, 80, 70], 15), ('ls', [86, 76, 69], 16),
       ('ww', [22, 11, 34], 17)],
      dtype=[('f0', '<U3'), ('f1', '<i4', (3,)), ('f2', '<i4')])

In [53]:
i[2]['f0']

'ww'

In [55]:
i[2]['f1'][2]

34

In [66]:
# 第二种设置dtype属性的方式
# 设置第一个每个字段的类型 别名 以及长度
j = np.array(data,dtype=[
    ('name','str_',2),
    ('scores','int32',3),
    ('age','int32',1)]
            )
j

array([('zs', [90, 80, 70], 15), ('ls', [86, 76, 69], 16),
       ('ww', [22, 11, 34], 17)],
      dtype=[('name', '<U2'), ('scores', '<i4', (3,)), ('age', '<i4')])

In [65]:
j['name'][1]

'ls'

In [69]:
# 第三种设置dtype的方式
k = np.array(data,dtype={
    'names':['name','score','age'],
    'formats':['U3','3int32','int32']
})
k

array([('zs', [90, 80, 70], 15), ('ls', [86, 76, 69], 16),
       ('ww', [22, 11, 34], 17)],
      dtype=[('name', '<U3'), ('score', '<i4', (3,)), ('age', '<i4')])

In [70]:
# 第四种 设置dtype 的方式
# 0 ，16 ， 28 表示数据存储事的字节偏移位置
# 在0 字节位置输出name,16字节
l  = np.array(data, dtype={
    'name':('U3',0),
    'scores':('3int32',16),
    'age':('int32',28)
})
l

array([('zs', [90, 80, 70], 15), ('ls', [86, 76, 69], 16),
       ('ww', [22, 11, 34], 17)],
      dtype={'names':['name','scores','age'], 'formats':['<U3',('<i4', (3,)),'<i4'], 'offsets':[0,16,28], 'itemsize':32})

### ndarray数组中存放日期类型数据

In [76]:
m = np.array(['2011','2012-01-01',
             '2013-11-11 11:11:11','2013-01-01'])
m

array(['2011', '2012-01-01', '2013-11-11 11:11:11', '2013-01-01'],
      dtype='<U19')

In [82]:
# 将其改为时间类型 -是numpy默认的一种日期时间格式
m = m.astype('M8[D]')
# M8 【h s】 都可以
m
# datetime64[D] : 描述时间（精确到day）

array(['2011-01-01', '2012-01-01', '2013-11-11', '2013-01-01'],
      dtype='datetime64[D]')

In [81]:
m[3]+ 1

numpy.datetime64('2013-01-02')

In [83]:
m[3] - m[1]

numpy.timedelta64(366,'D')

### 类型字符码 
    类型                       字符码
    np.bool_              ?                         
    np.int8/16/32/64    i1/i2/i4/i8               
    np.uint8/16/32/64   u1/u2/u4/u8               
    np.float16/32/64    f2/f4/f8                  
    np.complex64/128    c8/c16                    
    np.str_             U<字符数>                 
    np.datetime64       M8[Y / M / D / h / m / s] 


### ndarray 数组对象的维度操作
    视图变维(数据共享) ary.reshape() ary.ravel()
    复制变维(拥有独立的数据) a.flattern(0 a.copy()
    就地变维 直接改变原数据的维度 a.shape() a.resize()
    

In [87]:
# 视图变维的时候，会修改之前的数据。用同一个数据
n = np.arange(1,9)
n.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
n

array([1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
n.reshape(2,4).ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [92]:
# 复制变维
o = np.arange(1,9).reshape(2,4)
o

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
p = o.flatten()

In [96]:
p[1] = 100
p

array([  1, 100,   3,   4,   5,   6,   7,   8])

In [97]:
o

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [100]:
p.resize(2,2,2)
p

array([[[  1, 100],
        [  3,   4]],

       [[  5,   6],
        [  7,   8]]])

### ndarray 对象的切片操作
    数组对象的切片与列表切片参数含义相似
    步长+ ： 从前向后切
    步长为-：从后向前切
    ary[起始位置：终止位置：步长]

In [102]:
q = np.arange(1,10)
q

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
q[:3]

array([1, 2, 3])

In [104]:
q[3:6]

array([4, 5, 6])

In [105]:
q[6:]

array([7, 8, 9])

In [106]:
q[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [107]:
q[:-4:-1]

array([9, 8, 7])

In [108]:
q[-4:-7:-1]

array([6, 5, 4])

In [109]:
q[-7::-1]

array([3, 2, 1])

In [110]:
q[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
q[::3]

array([1, 4, 7])

In [112]:
q[1::3]

array([2, 5, 8])

### 多维数组的切片操作
    以，作为分隔符，分别对页/行/列 每一维度执行切片
    ary[::,::,...]

In [120]:
r = np.arange(1,17).reshape(4,2,2)
r

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [124]:
r[1,1,1]

8

In [125]:
r[1,1,:]

array([7, 8])

### ndarray 数组的掩码操作

In [133]:
s = np.arange(1,10)
mask = (s%2 == 0)
s[mask]

array([2, 4, 6, 8])

In [135]:
# 输出100以内的3与7的倍数
t = np.arange(100)
t[(t%3 ==0) & (t%7 ==0)]

array([ 0, 21, 42, 63, 84])

### 多维数组的组合与拆分
    垂直方向执行组合操作
    c = np.vstack((a,b))
    垂直方向执行拆分操作
    a,b = np.vsplit(c,2)

In [139]:
u = np.arange(1,7).reshape(2,3)
v = np.arange(7,13).reshape(2,3)
w =np.vstack((u,v))
w

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [140]:
x,y = np.vsplit(w,2)

In [141]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [142]:
y

array([[ 7,  8,  9],
       [10, 11, 12]])

#### 水平方向的组合与拆分

In [144]:
z = np.hstack((u,v))
z

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [146]:
a1,a2 = np.hsplit(z,2)
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [148]:
# 深度方向的组合与拆分
a3 = np.dstack((u,v))
a3

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [149]:
a3.shape

(2, 3, 2)

In [150]:
a4,a5 = np.dsplit(a3,2)

In [151]:
print(a4)
print(a5)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[[[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


### 组合与拆分的相关函数
    以axis作为轴向 把a与b进行组合操作
    c = np.concatenate((a,b),axis =0)
    以axis 作为轴向，把c拆成两部分 a 与 b
    a,b = np.split(c,x,axis = 0)
