In [1]:
import numpy as np

### 创建数组

In [12]:
a = [1,2,3,4,5,6]
b = np.array(a)
b


array([1, 2, 3, 4, 5, 6])

In [7]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [10]:
np.array([3, 4, 2, 3.14])

array([3.  , 4.  , 2.  , 3.14])

In [13]:
np.array(['nihao','wpmen',123])

array(['nihao', 'wpmen', '123'], dtype='<U5')

In [14]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [15]:
np.array([range(i, i + 3) for i in [1, 5, 10]])

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [10, 11, 12]])

In [16]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.zeros((3, 5), dtype=float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones((2,4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.ones(10,dtype=float)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [26]:
np.full((3, 5), 'haha')

array([['haha', 'haha', 'haha', 'haha', 'haha'],
       ['haha', 'haha', 'haha', 'haha', 'haha'],
       ['haha', 'haha', 'haha', 'haha', 'haha']], dtype='<U4')

In [27]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
np.linspace(0, 1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [32]:
np.random.random((2, 2))

array([[0.32408551, 0.38448842],
       [0.46157336, 0.67681802]])

In [35]:
np.random.normal(0, 1,10)

array([-0.7775034 , -2.80235722,  0.38742176, -0.34604882,  0.48679081,
        1.57361521, -1.18428685, -0.33859573,  1.58450184, -0.22545445])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [42]:
np.empty((2,3))

array([[0.24073598, 0.59666094, 0.45307206],
       [0.35946324, 0.85487091, 0.09431105]])

### 切片与索引

In [46]:
c = np.random.randint(10,size=8)
c

array([7, 5, 5, 4, 2, 1, 2, 2])

In [48]:
c[1]

5

In [59]:
c[0] = 3.1415
c

array([3, 5, 5, 4, 2, 1, 2, 2])

In [49]:
c[-2]

2

In [53]:
d = np.random.randint(14, size=(3, 4))

In [54]:
d

array([[ 8, 11, 10, 11],
       [ 4, 13, 13, 13],
       [ 0,  7, 11,  1]])

In [56]:
d[0, 0] = 12

In [57]:
d

array([[12, 11, 10, 11],
       [ 4, 13, 13, 13],
       [ 0,  7, 11,  1]])

In [60]:
e = np.arange(10)

In [61]:
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
x2 = np.random.randint(10, size=(3, 4))
x2

array([[2, 9, 5, 1],
       [9, 8, 3, 9],
       [6, 3, 4, 3]])

In [63]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [64]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [65]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [66]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [18]:
b = [-4, -2, 0, 2, 4]
a = np.array(b)

In [19]:
a

array([-4, -2,  0,  2,  4])

In [20]:
np.absolute(a)

array([4, 2, 0, 2, 4])

In [23]:
print(np.add(a,2))
print(np.subtract(a,4))
print(np.negative(a))
print(np.multiply(a,3))
print(np.divide(a,3))
print(np.floor_divide(a,2))
print(np.power(a,4))
print(np.mod(a,3))

[-2  0  2  4  6]
[-8 -6 -4 -2  0]
[ 4  2  0 -2 -4]
[-12  -6   0   6  12]
[-1.33333333 -0.66666667  0.          0.66666667  1.33333333]
[-2 -1  0  1  2]
[256  16   0  16 256]
[2 1 0 2 1]


### 三角函数

In [27]:
c = np.linspace(0,np.pi,4)
c

array([0.        , 1.04719755, 2.0943951 , 3.14159265])

In [28]:
print("theta      = ", c)
print("sin(theta) = ", np.sin(c))
print("cos(theta) = ", np.cos(c))
print("tan(theta) = ", np.tan(c))

theta      =  [0.         1.04719755 2.0943951  3.14159265]
sin(theta) =  [0.00000000e+00 8.66025404e-01 8.66025404e-01 1.22464680e-16]
cos(theta) =  [ 1.   0.5 -0.5 -1. ]
tan(theta) =  [ 0.00000000e+00  1.73205081e+00 -1.73205081e+00 -1.22464680e-16]
