# 数组类型

In [1]:
import numpy as np

### 类型转换

In [10]:
a = np.array([1,5,-3],dtype=float)
a

array([ 1.,  5., -3.])

### asarray()函数

In [13]:
b = np.array([1,2,3])   #将int类型转换为float
np.asarray(b,dtype=float)

array([1., 2., 3.])

### astype（）函数    返回一个新的数组

In [17]:
c = np.array([1,2,3])
c.astype(float)

array([1., 2., 3.])

## 数组的操作

In [48]:
# 电影名称
mv_name = ['肖申克的救赎','控方证人','美丽人生','霸王别姬','阿甘正传','泰坦尼克号','辛德勒的名单','这个杀手不太冷']

In [26]:
## 评分人数
mv_num = np.array([3214,34235,5436,43655,756765,534534,3254,567457])

In [28]:
## 评分
mv_score = np.array([9.6,9.5,9.4,9.4,9.3,9.1,9.0,9.0])

In [29]:
## 电影时长
mv_time = np.array([112,123,122,110,112,125,142,126])

###  数组排序

In [31]:
np.sort(mv_num)  #从小到大排序

array([  3214,  34235,   5436,  43655, 756765, 534534,   3254, 567457])

In [35]:
order = np.argsort(mv_num)  #返回原数组的从小到大排列的索引
order

array([0, 6, 2, 1, 3, 5, 7, 4], dtype=int64)

In [49]:
mv_name[order[0]]  #来返回最少的评论人数的电影名

'肖申克的救赎'

In [50]:
np.sum(mv_num)   #求和

1948550

In [51]:
mv_num.sum()

1948550

In [52]:
np.max(mv_time)  #求最大值 

142

In [53]:
mv_time.max()

142

In [54]:
mv_score.min()  #求最小值

9.0

In [55]:
np.min(mv_score)

9.0

In [58]:
mv_time.mean()   #求取平均值

121.5

In [57]:
np.mean(mv_time)

121.5

In [59]:
np.std(mv_time)   #标准差

9.797958971132712

In [60]:
mv_time.std()

9.797958971132712

In [61]:
np.cov(mv_time,mv_score)  #相关系数矩阵

array([[ 1.09714286e+02, -1.69285714e+00],
       [-1.69285714e+00,  5.26785714e-02]])

## 多维数组的操作

In [63]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [66]:
a.shape=2,3   #定义数组的类型   改变了原来数组的类型
a

array([[0, 1, 2],
       [3, 4, 5]])

In [67]:
a.shape   #查看数组的维度

(2, 3)

In [70]:
b = np.arange(6)
b

array([0, 1, 2, 3, 4, 5])

In [73]:
b.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [74]:
b

array([0, 1, 2, 3, 4, 5])

### 转置

In [77]:
c = b.reshape(2,3) 
c

array([[0, 1, 2],
       [3, 4, 5]])

In [78]:
c.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [79]:
c.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [80]:
c

array([[0, 1, 2],
       [3, 4, 5]])

### 数组链接
#### 有时候我们需要将数组按照一定顺序拼接：
#### concatenate（(a0，a1,a2.......aN,axis=0）

In [83]:
x = np.array([[0,1,2],[10,11,12]])
y = np.array([[20,21,22],[30,31,32]])
print(x.shape)
print(y.shape)

(2, 3)
(2, 3)


#### 根据第一维进行链接

In [84]:
z = np.concatenate((x,y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [86]:
z = np.concatenate((x,y),axis=1)  #按照第二维度进行拼接
z

array([[ 0,  1,  2, 20, 21, 22],
       [10, 11, 12, 30, 31, 32]])

In [87]:
z = np.array((x,y))   #拼接成三维数组
z

array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[20, 21, 22],
        [30, 31, 32]]])

### 事实上，Numpy给我们提供了对应这三种情况的函数

#### vstack
#### hstack
#### dstack

In [88]:
np.vstack((x,y))

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [89]:
np.hstack((x,y))

array([[ 0,  1,  2, 20, 21, 22],
       [10, 11, 12, 30, 31, 32]])

In [90]:
np.dstack((x,y))

array([[[ 0, 20],
        [ 1, 21],
        [ 2, 22]],

       [[10, 30],
        [11, 31],
        [12, 32]]])

#### 求绝对值

In [91]:
a = np.array([-1,2,3,-2])
np.abs(a)

array([1, 2, 3, 2])